# Generated by Django 2.2.1 on 2019-11-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoModel',
        ),
    ]
